"""create initial database tables

Revision ID: 1c53ea6691c7
Revises:
Create Date: 2026-09-06 02:41:10.856411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c53ea6691c7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('factory_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('weekly_closure_day', sa.String(length=20), nullable=False),
    sa.Column('dataset_provenance', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id')
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_version', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('ix_risk_events_line_snapshot', 'risk_events', ['line_id', 'snapshot_at'], unique=False)
    op.create_table('production_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.String(length=50), nullable=False),
    sa.Column('factory_id', sa.String(length=50), nullable=False),
    sa.Column('line_name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('standard_operator_capacity', sa.Integer(), nullable=False),
    sa.Column('planning_efficiency', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('dataset_provenance', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.factory_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id')
    )
    op.create_index(op.f('ix_production_lines_factory_id'), 'production_lines', ['factory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_lines_factory_id'), table_name='production_lines')
    op.drop_table('production_lines')
    op.drop_index('ix_risk_events_line_snapshot', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('factories')
    # ### end Alembic commands ###
